# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-FOkZbIl_402X43ygmXdcyhKNxQINrI6
"""

# Kelvin derecesini santigrat dereceye çevirme algoritması

def kelvin_cevir(kelvin):
  # Kelvin derecesini santigrat dereceye çevirme formülü
  santigrat = kelvin - 273
  return santigrat

# Kelvin derecesini kullanıcıdan al
kelvin = int(input("Kelvin derecesini girin: "))

# Kelvin derecesini santigrat dereceye çevir
santigrat = kelvin_cevir(kelvin)

# Çıktı ver
print(f"{kelvin} Kelvin {santigrat} Santigrat dereceye eşittir.")

# Daire çevresini ve alanını hesaplayan algoritma
from math import pi

def daire_cevre(yaricap):
  # Dairenin çevresini hesaplama formülü
  çevre = 2 * pi * yaricap
  return çevre

def daire_alan(yaricap):
  # Dairenin alanını hesaplama formülü
  alan = pi * yaricap ** 2
  return alan

# İşlemi seç
print("Yapmak istediğiniz işlemi seçiniz:")
print("1 - Daire çevresi hesapla")
print("2 - Daire alanı hesapla")
islem = int(input())

# Kullanıcıdan yarıçapı al
yaricap = float(input("Dairenin yarıçapını giriniz (cm): "))

# İşlemi uygula
if (islem == 1):
  # Dairenin çevresini hesapla
  çevre = daire_cevre(yaricap)
  # Çıktı ver
  print(f"Yarıçapı {yaricap} cm olan dairenin çevresi: {çevre:.2f} cm")
elif (islem == 2):
  # Dairenin alanını hesapla
  alan = daire_alan(yaricap)
  # Çıktı ver
  print(f"Yarıçapı {yaricap} cm olan dairenin alanı: {alan:.2f} cm²")

# Sayıların basamaklarını toplayan algoritma

print("Bu algoritma, girilen dört basamaklı bir sayının ilk ve son basamaklarının toplamını hesaplar.")

while True:
    try:
        sayi = int(input("Dört basamaklı bir sayı giriniz:"))
    except ValueError:
        print("Lütfen dört basamaklı bir sayı giriniz.")
        continue

    if (sayi > 999) and (sayi < 10000):
        break

# İlk ve son basamakları bul
ilk_basamak = int(sayi / 1000)
son_basamak = int(sayi % 10)

# Basamakların toplamını hesapla
basamak_toplami = ilk_basamak + son_basamak

# Çıktı ver
print(f"İlk basamak değeri: {ilk_basamak}")
print(f"Son basamak değeri: {son_basamak}")
print(f"İlk ve son basamakların toplamı: {basamak_toplami}")

# Programı sonlandır
print("Programdan çıkılıyor.")

# Verilen hiza ve mesafeye göre seyahatin zamanını hesaplayan algoritma

print("Bu algoritma, verilen hiza ve mesafeye göre seyahatin zamanını hesaplar.")

toplam_mesafe = int(input("Toplam yol alacağınız mesafeyi giriniz (km): "))
araba_hiz = int(input("Arabanızın hızını giriniz (km/s): "))

# Seyahatin süresini dakika cinsinden hesapla
seyahat_suresi_dakika = toplam_mesafe / araba_hiz * 60

# Seyahatin süresini saat cinsinden hesapla
seyahat_suresi_saat = toplam_mesafe / araba_hiz

# Çıktı ver
print(f"{araba_hiz} km/s hızla {toplam_mesafe} km'lik yolu {seyahat_suresi_dakika:.2f} dakikada veya {seyahat_suresi_saat:.2f} saatte gidersiniz.")